<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationInsightsResourceId>/subscriptions/788c8c3a-25b8-4ec9-ac01-8f891f7f4844/resourceGroups/RG-App-Infra-DEV/providers/microsoft.insights/components/app-service-test</ApplicationInsightsResourceId>
    <UserSecretsId>540c82de-7ba0-4742-b27f-77d45c53d8f5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.27.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.23.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.4" />
  </ItemGroup>

</Project>
